### ISSUE TITLE
Fix documentation deployment strategy

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/march-iv#193]
Currently the documentation hosted on https://project-march.github.io/march-iv/ is deployed by any travis build on the march-iv develop branch which isn't triggered by a submodule per the following logic in the `.travis.yml`

```
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: march_ws/docs/build/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: develop
condition: !$DEPENDENT_BUILD
```

Currently this means that a merged pr including documenation in a submodule does NOT update the live documentation. This is a clear problem that can be fixed in a number of ways:

#### The easy way
Remove the `condition: !$DEPENDENT_BUILD` to let each pr trigger a new documentation deployment. This would let each pr trigger a new documentation build. Still incorrect as it shows documentation for non-implemented features from the pr. Although there is less chance of the docs becoming outdated.

#### The correct way
Configure a deployment build with the `.travis.yml` (still kind of a work around as [travis does not support multiple .yml files](https://stackoverflow.com/questions/32765652/is-it-possible-to-run-2-seperate-travis-yml-files-from-the-same-github-reposito).
Add a deploy script to the `.travis.yml` of each submodule so they can all deploy the documentation on a new commit to develop.

#### The lazy way
Accept it. This is what we are currently doing. It is not ideal but with how often the main repo gets updated it is not a problem. Combined with the fact that the documentation is not written for us and that you can generate it offline means we probably won't fix it anytime soon.
