### ISSUE TITLE
Refactor march_hardware to easily switch between hardware configurations

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/march-iv#195]
Use yaml-cpp to create a MarchRobot object from .yaml files that look like this.

```
march3:
  ifName: enps02
  ecatCycleTime: 4
  joints:
    - left_hip:
        imc:
          slaveIndex: 1
          encoder:
            resolution: 16
            minPositionIU: 22134
            maxPositionIU: 43436
            zeroPositionIU: 24515
            safetyMarginRad: 0.05
    - right_hip:
        imc:
          slaveIndex: 2
          encoder:
            resolution: 16
            minPositionIU: 22134
            maxPositionIU: 43436
            zeroPositionIU: 24515
            safetyMarginRad: 0.05
```

This builder should be able to parse any well-formed .yaml file and create joints accordingly.
